// AUTO-GENERATED. Do not edit by hand.
import AddPlus from './components/AddPlus.svelte';
import Bookmark from './components/Bookmark.svelte';
import Checkmark from './components/Checkmark.svelte';
import Close from './components/Close.svelte';
import Copy from './components/Copy.svelte';
import Cut from './components/Cut.svelte';
import Download from './components/Download.svelte';
import File from './components/File.svelte';
import Filter from './components/Filter.svelte';
import Heart from './components/Heart.svelte';
import Info from './components/Info.svelte';
import Leaf from './components/Leaf.svelte';
import Link from './components/Link.svelte';
import Minus from './components/Minus.svelte';
import Moon from './components/Moon.svelte';
import Paste from './components/Paste.svelte';
import Pencil from './components/Pencil.svelte';
import Pin from './components/Pin.svelte';
import Refresh from './components/Refresh.svelte';
import Save from './components/Save.svelte';
import Search from './components/Search.svelte';
import Settings from './components/Settings.svelte';
import Sort from './components/Sort.svelte';
import Star from './components/Star.svelte';
import Sun from './components/Sun.svelte';
import Tag from './components/Tag.svelte';
import Trash from './components/Trash.svelte';
import TreePalm from './components/TreePalm.svelte';
import TreePine from './components/TreePine.svelte';
import Upload from './components/Upload.svelte';
import User from './components/User.svelte';

export { AddPlus, Bookmark, Checkmark, Close, Copy, Cut, Download, File, Filter, Heart, Info, Leaf, Link, Minus, Moon, Paste, Pencil, Pin, Refresh, Save, Search, Settings, Sort, Star, Sun, Tag, Trash, TreePalm, TreePine, Upload, User };

export const iconRegistry = {
  "add-plus": { component: AddPlus, meta: {"name":"add-plus","displayName":"Add Plus","description":"Represents creating, adding, or inserting a new item.","keywords":["add","plus","create","new","insert","increase"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "bookmark": { component: Bookmark, meta: {"name":"bookmark","displayName":"Bookmark","description":"Represents saving or marking content for later reference.","keywords":["bookmark","favorite","save","mark","reading","flag"],"categories":["System","Content"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "checkmark": { component: Checkmark, meta: {"name":"checkmark","displayName":"Checkmark","description":"Indicates success, completion, or a confirmed action.","keywords":["check","checkmark","done","complete","confirm","success"],"categories":["System","Status"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "close": { component: Close, meta: {"name":"close","displayName":"Close","description":"Represents closing, dismissing, or cancelling a dialog or action.","keywords":["close","x","cancel","dismiss","clear","exit"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "copy": { component: Copy, meta: {"name":"copy","displayName":"Copy","description":"Represents copying content to the clipboard or duplicating an item.","keywords":["copy","duplicate","clipboard","clone","document"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "cut": { component: Cut, meta: {"name":"cut","displayName":"Cut","description":"Represents cutting content or removing it while copying to the clipboard.","keywords":["cut","scissors","remove","clipboard","edit"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "download": { component: Download, meta: {"name":"download","displayName":"Download","description":"Represents downloading or saving content from the cloud or web.","keywords":["download","save","arrow-down","cloud","file"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "file": { component: File, meta: {"name":"file","displayName":"File","description":"Represents a generic file or document.","keywords":["file","document","page","doc","sheet"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "filter": { component: Filter, meta: {"name":"filter","displayName":"Filter","description":"Represents filtering, narrowing, or refining a list of results.","keywords":["filter","funnel","refine","narrow","search"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "heart": { component: Heart, meta: {"name":"heart","displayName":"Heart","description":"Represents liking, favoriting, or expressing appreciation.","keywords":["heart","like","favorite","love","save"],"categories":["System","Reactions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "info": { component: Info, meta: {"name":"info","displayName":"Info","description":"Represents informational content or help.","keywords":["info","information","details","help","about"],"categories":["System","Status"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "leaf": { component: Leaf, meta: {"name":"leaf","displayName":"Leaf","description":"Represents nature, sustainability, or eco-friendly content.","keywords":["leaf","nature","eco","green","plant"],"categories":["Nature","Status"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "link": { component: Link, meta: {"name":"link","displayName":"Link","description":"Represents a hyperlink or connection between items.","keywords":["link","url","chain","hyperlink","connect"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "minus": { component: Minus, meta: {"name":"minus","displayName":"Minus","description":"Represents removing, subtracting, or decreasing an item or value.","keywords":["minus","remove","subtract","decrease","dash"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "moon": { component: Moon, meta: {"name":"moon","displayName":"Moon","description":"Represents night mode, dark mode, or nighttime.","keywords":["moon","night","dark-mode","theme","sleep"],"categories":["System","Weather"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "paste": { component: Paste, meta: {"name":"paste","displayName":"Paste","description":"Represents pasting content from the clipboard.","keywords":["paste","clipboard","insert","document","edit"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "pencil": { component: Pencil, meta: {"name":"pencil","displayName":"Pencil","description":"Represents editing or writing content.","keywords":["pencil","edit","write","annotation","compose"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "pin": { component: Pin, meta: {"name":"pin","displayName":"Pin","description":"Represents pinning or keeping an item at the top or in view.","keywords":["pin","pinned","stick","location","top"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "refresh": { component: Refresh, meta: {"name":"refresh","displayName":"Refresh","description":"Represents reloading content or syncing data.","keywords":["refresh","reload","sync","update","reload-page"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "save": { component: Save, meta: {"name":"refresh","displayName":"Refresh","description":"Represents reloading content or syncing data.","keywords":["refresh","reload","sync","update","reload-page"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "search": { component: Search, meta: {"name":"search","displayName":"Search","description":"Represents searching, finding, or querying content.","keywords":["search","find","magnifying-glass","lookup","query"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "settings": { component: Settings, meta: {"name":"settings","displayName":"Settings","description":"Represents settings, configuration, or preferences.","keywords":["settings","gear","cog","preferences","configuration"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "sort": { component: Sort, meta: {"name":"sort","displayName":"Sort","description":"Represents sorting items by a selected order.","keywords":["sort","order","reorder","ascending","descending"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "star": { component: Star, meta: {"name":"star","displayName":"Star","description":"Represents highlighting, rating, or favoriting an item.","keywords":["star","favorite","rating","highlight","featured"],"categories":["System","Reactions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "sun": { component: Sun, meta: {"name":"sun","displayName":"Sun","description":"Represents day mode, light mode, or daytime.","keywords":["sun","day","light-mode","theme","weather"],"categories":["System","Weather"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "tag": { component: Tag, meta: {"name":"tag","displayName":"Tag","description":"Represents labeling, tagging, or categorizing content.","keywords":["tag","label","category","badge","metadata"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "trash": { component: Trash, meta: {"name":"trash","displayName":"Trash","description":"Represents deleting or discarding an item.","keywords":["trash","delete","remove","bin","garbage"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "tree-palm": { component: TreePalm, meta: {"name":"tree-palm","displayName":"Tree Palm","description":"Represents a palm tree, tropical locations, or vacation themes.","keywords":["tree","palm","tropical","beach","vacation"],"categories":["Nature","Travel"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "tree-pine": { component: TreePine, meta: {"name":"tree-pine","displayName":"Tree Pine","description":"Represents an evergreen or pine tree, forests, or outdoor themes.","keywords":["tree","pine","evergreen","forest","outdoors"],"categories":["Nature","Outdoors"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "upload": { component: Upload, meta: {"name":"upload","displayName":"Upload","description":"Represents uploading or sending content to the cloud or a server.","keywords":["upload","send","arrow-up","cloud","file"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "user": { component: User, meta: {"name":"user","displayName":"User","description":"Represents a person, profile, or user account.","keywords":["user","person","profile","account","avatar"],"categories":["System","User"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} }
} as const;

export type IconName = keyof typeof iconRegistry;
