// AUTO-GENERATED. Do not edit by hand.
import AddPlus from './components/AddPlus.svelte';
import AlignLeft from './components/AlignLeft.svelte';
import AlignMiddle from './components/AlignMiddle.svelte';
import AlignRight from './components/AlignRight.svelte';
import ArrowDown from './components/ArrowDown.svelte';
import ArrowLeft from './components/ArrowLeft.svelte';
import ArrowRight from './components/ArrowRight.svelte';
import ArrowUp from './components/ArrowUp.svelte';
import Bee from './components/Bee.svelte';
import Beehive from './components/Beehive.svelte';
import Blackhole from './components/Blackhole.svelte';
import Bookmark from './components/Bookmark.svelte';
import Bug from './components/Bug.svelte';
import BugOff from './components/BugOff.svelte';
import ChartBar from './components/ChartBar.svelte';
import ChartCandlestick from './components/ChartCandlestick.svelte';
import ChartGnatt from './components/ChartGnatt.svelte';
import Chart from './components/Chart.svelte';
import ChartPie from './components/ChartPie.svelte';
import ChartScatter from './components/ChartScatter.svelte';
import Checkmark from './components/Checkmark.svelte';
import CheveronDown from './components/CheveronDown.svelte';
import CheveronLeft from './components/CheveronLeft.svelte';
import CheveronRight from './components/CheveronRight.svelte';
import CheveronUp from './components/CheveronUp.svelte';
import Close from './components/Close.svelte';
import ClosedCaptions from './components/ClosedCaptions.svelte';
import CloudUpload from './components/CloudUpload.svelte';
import Colorblind from './components/Colorblind.svelte';
import Contrast from './components/Contrast.svelte';
import Copy from './components/Copy.svelte';
import Cut from './components/Cut.svelte';
import Database from './components/Database.svelte';
import Download from './components/Download.svelte';
import EyeOff from './components/EyeOff.svelte';
import EyeOn from './components/EyeOn.svelte';
import File from './components/File.svelte';
import Filter from './components/Filter.svelte';
import GitBranch from './components/GitBranch.svelte';
import Hammer from './components/Hammer.svelte';
import Heart from './components/Heart.svelte';
import Home from './components/Home.svelte';
import Honeycomb from './components/Honeycomb.svelte';
import Info from './components/Info.svelte';
import Layers from './components/Layers.svelte';
import Leaf from './components/Leaf.svelte';
import Link from './components/Link.svelte';
import Menu from './components/Menu.svelte';
import Minus from './components/Minus.svelte';
import Moon from './components/Moon.svelte';
import Paste from './components/Paste.svelte';
import Pencil from './components/Pencil.svelte';
import Person from './components/Person.svelte';
import Pin from './components/Pin.svelte';
import Refresh from './components/Refresh.svelte';
import Save from './components/Save.svelte';
import Search from './components/Search.svelte';
import Settings from './components/Settings.svelte';
import Sort from './components/Sort.svelte';
import Star from './components/Star.svelte';
import Sun from './components/Sun.svelte';
import Tag from './components/Tag.svelte';
import Terminal from './components/Terminal.svelte';
import Transgender from './components/Transgender.svelte';
import Translate from './components/Translate.svelte';
import Trash from './components/Trash.svelte';
import TreePalm from './components/TreePalm.svelte';
import TreePine from './components/TreePine.svelte';
import Upload from './components/Upload.svelte';
import User from './components/User.svelte';
import Wormhole from './components/Wormhole.svelte';
import Wrench from './components/Wrench.svelte';

export { AddPlus, AlignLeft, AlignMiddle, AlignRight, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Bee, Beehive, Blackhole, Bookmark, Bug, BugOff, ChartBar, ChartCandlestick, ChartGnatt, Chart, ChartPie, ChartScatter, Checkmark, CheveronDown, CheveronLeft, CheveronRight, CheveronUp, Close, ClosedCaptions, CloudUpload, Colorblind, Contrast, Copy, Cut, Database, Download, EyeOff, EyeOn, File, Filter, GitBranch, Hammer, Heart, Home, Honeycomb, Info, Layers, Leaf, Link, Menu, Minus, Moon, Paste, Pencil, Person, Pin, Refresh, Save, Search, Settings, Sort, Star, Sun, Tag, Terminal, Transgender, Translate, Trash, TreePalm, TreePine, Upload, User, Wormhole, Wrench };

export const iconRegistry = {
  "add-plus": { component: AddPlus, meta: {"name":"add-plus","displayName":"Add Plus","description":"Represents creating, adding, or inserting a new item.","keywords":["add","plus","create","new","insert","increase"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "align-left": { component: AlignLeft, meta: {"name":"align-left","displayName":"Align Left","description":"Represents left text alignment or positioning content to the left.","keywords":["align","left","text","alignment","justify","format"],"categories":["System","Text"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "align-middle": { component: AlignMiddle, meta: {"name":"align-middle","displayName":"Align Middle","description":"Icon for middle vertical alignment of text or elements.","keywords":["align","middle","vertical","center","alignment","text"],"categories":["Editor","Layout"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "align-right": { component: AlignRight, meta: {"name":"align-right","displayName":"Align Right","description":"Aligns text or content to the right side of a container.","keywords":["align","right","text","alignment","format","justify"],"categories":["System","Text"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "arrow-down": { component: ArrowDown, meta: {"name":"arrow-down","displayName":"Arrow Down","description":"Indicates movement or direction downward, often used for scroll or sort.","keywords":["arrow","down","descend","scroll down","sort descending","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "arrow-left": { component: ArrowLeft, meta: {"name":"arrow-left","displayName":"Arrow Left","description":"Indicates movement, navigation, or direction to the left.","keywords":["arrow","left","back","previous","navigate","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "arrow-right": { component: ArrowRight, meta: {"name":"arrow-right","displayName":"Arrow Right","description":"Indicates movement, navigation, or direction to the right.","keywords":["arrow","right","forward","next","navigate","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "arrow-up": { component: ArrowUp, meta: {"name":"arrow-up","displayName":"Arrow Up","description":"Indicates movement or direction upward, often used for scroll or sort.","keywords":["arrow","up","ascend","scroll up","sort ascending","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "bee": { component: Bee, meta: {"name":"bee","displayName":"Bee","description":"Represents a bee, often used for nature, productivity, or swarm concepts.","keywords":["bee","insect","pollinator","nature","honey","productivity"],"categories":["Objects","Nature"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "beehive": { component: Beehive, meta: {"name":"beehive","displayName":"Beehive","description":"Represents a beehive or hive, often used for teamwork, community, or storage.","keywords":["beehive","hive","bees","honey","community","teamwork"],"categories":["Objects","Nature"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "blackhole": { component: Blackhole, meta: {"name":"blackhole","displayName":"Blackhole","description":"Represents saving or marking content for later reference.","keywords":["blackhole","space","astronomy","cosmos","gravity","event horizon"],"categories":["Nature","Space"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "bookmark": { component: Bookmark, meta: {"name":"bookmark","displayName":"Bookmark","description":"Represents saving or marking content for later reference.","keywords":["bookmark","favorite","save","mark","reading","flag"],"categories":["System","Content"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "bug": { component: Bug, meta: {"name":"bug","displayName":"Bug","description":"Represents software bugs, issues, or error reporting.","keywords":["bug","error","issue","defect","problem","debug"],"categories":["System","Development"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "bug-off": { component: BugOff, meta: {"name":"bug-off","displayName":"Bug Off","description":"Represents debugging turned off, bug-free state, or disabling error tracking.","keywords":["bug","debug","off","disable","error","fix","resolved"],"categories":["System","Development"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "chart-bar": { component: ChartBar, meta: {"name":"chart-bar","displayName":"Chart Bar","description":"Represents bar charts for comparing discrete values or categories.","keywords":["chart","bar","analytics","data","metrics","report","dashboard"],"categories":["Data","Charts"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "chart-candlestick": { component: ChartCandlestick, meta: {"name":"chart-candlestick","displayName":"Chart Candlestick","description":"Represents candlestick charts for financial or trading data.","keywords":["chart","candlestick","finance","trading","stocks","ohlc","market"],"categories":["Data","Charts"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "chart-gnatt": { component: ChartGnatt, meta: {"name":"chart-gantt","displayName":"Chart Gantt","description":"Represents Gantt charts for project timelines, tasks, and dependencies.","keywords":["chart","gantt","timeline","project","tasks","scheduling","dependencies"],"categories":["Data","Charts"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "chart": { component: Chart, meta: {"name":"chart","displayName":"Chart","description":"","keywords":[],"categories":[],"variants":["stroke"],"sizes":[24],"version":"0.1.0","author":"Clothesline Studio","changelog":[]} },
  "chart-pie": { component: ChartPie, meta: {"name":"chart-pie","displayName":"Chart Pie","description":"Represents pie charts for showing parts of a whole.","keywords":["chart","pie","segments","distribution","analytics","data","proportion"],"categories":["Data","Charts"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "chart-scatter": { component: ChartScatter, meta: {"name":"chart-scatter","displayName":"Chart Scatter","description":"Represents scatter plots for correlations, distributions, or outliers.","keywords":["chart","scatter","points","distribution","analytics","data","statistics"],"categories":["Data","Charts"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "checkmark": { component: Checkmark, meta: {"name":"checkmark","displayName":"Checkmark","description":"Indicates success, completion, or a confirmed action.","keywords":["check","checkmark","done","complete","confirm","success"],"categories":["System","Status"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "cheveron-down": { component: CheveronDown, meta: {"name":"chevron-down","displayName":"Chevron Down","description":"Compact directional indicator for expanding content or scrolling down.","keywords":["chevron","down","expand","dropdown","accordion","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "cheveron-left": { component: CheveronLeft, meta: {"name":"chevron-left","displayName":"Chevron Left","description":"Compact directional indicator for going back or moving left.","keywords":["chevron","left","back","previous","navigate","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "cheveron-right": { component: CheveronRight, meta: {"name":"chevron-right","displayName":"Chevron Right","description":"Compact directional indicator for moving forward or to the right.","keywords":["chevron","right","forward","next","navigate","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "cheveron-up": { component: CheveronUp, meta: {"name":"chevron-up","displayName":"Chevron Up","description":"Compact directional indicator for collapsing content or scrolling up.","keywords":["chevron","up","collapse","accordion","expand less","direction"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "close": { component: Close, meta: {"name":"close","displayName":"Close","description":"Represents closing, dismissing, or cancelling a dialog or action.","keywords":["close","x","cancel","dismiss","clear","exit"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "closed-captions": { component: ClosedCaptions, meta: {"name":"closed-captions","displayName":"Closed Captions","description":"Represents closed captions or subtitles for audio and video content.","keywords":["closed captions","subtitles","cc","audio","video","accessibility"],"categories":["Media","Accessibility"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "cloud-upload": { component: CloudUpload, meta: {"name":"cloud-upload","displayName":"Cloud Upload","description":"Represents uploading content or data into the cloud.","keywords":["cloud","upload","sync","backup","import","file"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "colorblind": { component: Colorblind, meta: {"name":"colorblind","displayName":"Color Blind Mode","description":"Represents color vision accessibility modes such as protan, deutan, or tritan.","keywords":["colorblind","vision","accessibility","a11y","contrast","filters"],"categories":["System","Accessibility"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "contrast": { component: Contrast, meta: {"name":"contrast","displayName":"Contrast","description":"Represents contrast controls for themes, display settings, or accessibility.","keywords":["contrast","brightness","theme","display","accessibility","high contrast"],"categories":["System","Accessibility"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "copy": { component: Copy, meta: {"name":"copy","displayName":"Copy","description":"Represents copying content to the clipboard or duplicating an item.","keywords":["copy","duplicate","clipboard","clone","document"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "cut": { component: Cut, meta: {"name":"cut","displayName":"Cut","description":"Represents cutting content or removing it while copying to the clipboard.","keywords":["cut","scissors","remove","clipboard","edit"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "database": { component: Database, meta: {"name":"database","displayName":"Database","description":"Represents databases, storage systems, or data sources.","keywords":["database","data","storage","server","backend","tables"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "download": { component: Download, meta: {"name":"download","displayName":"Download","description":"Represents downloading or saving content from the cloud or web.","keywords":["download","save","arrow-down","cloud","file"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "eye-off": { component: EyeOff, meta: {"name":"eye-off","displayName":"Eye Off","description":"Represents hidden content, hide password, or disabled visibility.","keywords":["eye","hidden","hide","private","visibility","off"],"categories":["System","View"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "eye-on": { component: EyeOn, meta: {"name":"eye-on","displayName":"Eye On","description":"Represents visible content, show password, or enabled visibility.","keywords":["eye","view","visible","show","preview","visibility"],"categories":["System","View"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "file": { component: File, meta: {"name":"file","displayName":"File","description":"Represents a generic file or document.","keywords":["file","document","page","doc","sheet"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "filter": { component: Filter, meta: {"name":"filter","displayName":"Filter","description":"Represents filtering, narrowing, or refining a list of results.","keywords":["filter","funnel","refine","narrow","search"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "git-branch": { component: GitBranch, meta: {"name":"git-branch","displayName":"Git Branch","description":"Represents a git branch for version control and code management.","keywords":["git","branch","version control","repository","code"],"categories":["System","Development"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "hammer": { component: Hammer, meta: {"name":"hammer","displayName":"Hammer","description":"A hammer tool icon for construction and repair tasks.","keywords":["hammer","tool","construction","build","repair","hardware"],"categories":["Tools"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "heart": { component: Heart, meta: {"name":"heart","displayName":"Heart","description":"Represents liking, favoriting, or expressing appreciation.","keywords":["heart","like","favorite","love","save"],"categories":["System","Reactions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "home": { component: Home, meta: {"name":"home","displayName":"Home","description":"Represents the main dashboard, home screen, or starting point.","keywords":["home","dashboard","start","main","house","root"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "honeycomb": { component: Honeycomb, meta: {"name":"honeycomb","displayName":"Honeycomb","description":"Represents a hexagonal grid, cells, or a modular layout.","keywords":["honeycomb","hexagon","grid","cells","modules","structure"],"categories":["Layout","Objects"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "info": { component: Info, meta: {"name":"info","displayName":"Info","description":"Represents informational content or help.","keywords":["info","information","details","help","about"],"categories":["System","Status"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "layers": { component: Layers, meta: {"name":"layers","displayName":"Layers","description":"Represents stacked layers, levels, or grouped objects.","keywords":["layers","stack","levels","arrange","group","z-index"],"categories":["System","Layout"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "leaf": { component: Leaf, meta: {"name":"leaf","displayName":"Leaf","description":"Represents nature, sustainability, or eco-friendly content.","keywords":["leaf","nature","eco","green","plant"],"categories":["Nature","Status"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "link": { component: Link, meta: {"name":"link","displayName":"Link","description":"Represents a hyperlink or connection between items.","keywords":["link","url","chain","hyperlink","connect"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "menu": { component: Menu, meta: {"name":"menu","displayName":"Menu","description":"Represents a list of navigation options or actions, typically the main app menu.","keywords":["menu","navigation","hamburger","list","options","sidebar"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "minus": { component: Minus, meta: {"name":"minus","displayName":"Minus","description":"Represents removing, subtracting, or decreasing an item or value.","keywords":["minus","remove","subtract","decrease","dash"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "moon": { component: Moon, meta: {"name":"moon","displayName":"Moon","description":"Represents night mode, dark mode, or nighttime.","keywords":["moon","night","dark-mode","theme","sleep"],"categories":["System","Weather"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "paste": { component: Paste, meta: {"name":"paste","displayName":"Paste","description":"Represents pasting content from the clipboard.","keywords":["paste","clipboard","insert","document","edit"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "pencil": { component: Pencil, meta: {"name":"pencil","displayName":"Pencil","description":"Represents editing or writing content.","keywords":["pencil","edit","write","annotation","compose"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "person": { component: Person, meta: {"name":"person","displayName":"Person","description":"","keywords":[],"categories":[],"variants":["stroke"],"sizes":[24],"version":"0.1.0","author":"Clothesline Studio","changelog":[]} },
  "pin": { component: Pin, meta: {"name":"pin","displayName":"Pin","description":"Represents pinning or keeping an item at the top or in view.","keywords":["pin","pinned","stick","location","top"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "refresh": { component: Refresh, meta: {"name":"refresh","displayName":"Refresh","description":"Represents reloading content or syncing data.","keywords":["refresh","reload","sync","update","reload-page"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "save": { component: Save, meta: {"name":"refresh","displayName":"Refresh","description":"Represents reloading content or syncing data.","keywords":["refresh","reload","sync","update","reload-page"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "search": { component: Search, meta: {"name":"search","displayName":"Search","description":"Represents searching, finding, or querying content.","keywords":["search","find","magnifying-glass","lookup","query"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "settings": { component: Settings, meta: {"name":"settings","displayName":"Settings","description":"Represents settings, configuration, or preferences.","keywords":["settings","gear","cog","preferences","configuration"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "sort": { component: Sort, meta: {"name":"sort","displayName":"Sort","description":"Represents sorting items by a selected order.","keywords":["sort","order","reorder","ascending","descending"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "star": { component: Star, meta: {"name":"star","displayName":"Star","description":"Represents highlighting, rating, or favoriting an item.","keywords":["star","favorite","rating","highlight","featured"],"categories":["System","Reactions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "sun": { component: Sun, meta: {"name":"sun","displayName":"Sun","description":"Represents day mode, light mode, or daytime.","keywords":["sun","day","light-mode","theme","weather"],"categories":["System","Weather"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "tag": { component: Tag, meta: {"name":"tag","displayName":"Tag","description":"Represents labeling, tagging, or categorizing content.","keywords":["tag","label","category","badge","metadata"],"categories":["System","Data"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "terminal": { component: Terminal, meta: {"name":"terminal","displayName":"Terminal","description":"Represents a command line interface or terminal window.","keywords":["terminal","console","command","cli","shell","prompt"],"categories":["System","Development"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "transgender": { component: Transgender, meta: {"name":"transgender","displayName":"Transgender Symbol","description":"Represents transgender identity or related inclusive settings and content.","keywords":["transgender","gender","identity","inclusive","pride","symbol"],"categories":["Symbols","Accessibility"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "translate": { component: Translate, meta: {"name":"translate","displayName":"Translate","description":"Represents language translation or switching between languages.","keywords":["translate","language","localization","i18n","text","globe"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "trash": { component: Trash, meta: {"name":"trash","displayName":"Trash","description":"Represents deleting or discarding an item.","keywords":["trash","delete","remove","bin","garbage"],"categories":["System","Actions"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "tree-palm": { component: TreePalm, meta: {"name":"tree-palm","displayName":"Tree Palm","description":"Represents a palm tree, tropical locations, or vacation themes.","keywords":["tree","palm","tropical","beach","vacation"],"categories":["Nature","Travel"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "tree-pine": { component: TreePine, meta: {"name":"tree-pine","displayName":"Tree Pine","description":"Represents an evergreen or pine tree, forests, or outdoor themes.","keywords":["tree","pine","evergreen","forest","outdoors"],"categories":["Nature","Outdoors"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "upload": { component: Upload, meta: {"name":"upload","displayName":"Upload","description":"Represents uploading or sending content to the cloud or a server.","keywords":["upload","send","arrow-up","cloud","file"],"categories":["System","Files"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "user": { component: User, meta: {"name":"user","displayName":"User","description":"Represents a person, profile, or user account.","keywords":["user","person","profile","account","avatar"],"categories":["System","User"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} },
  "wormhole": { component: Wormhole, meta: {"name":"wormhole","displayName":"Wormhole","description":"Represents a portal, tunnel, or shortcut through space or complex systems.","keywords":["wormhole","portal","tunnel","teleport","space","gateway"],"categories":["System","Navigation"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-11-29"}]} },
  "wrench": { component: Wrench, meta: {"name":"wrench","displayName":"Wrench","description":"Represents tools, maintenance, settings, or configuration.","keywords":["wrench","tool","settings","configuration","maintenance","repair","adjust"],"categories":["System","Tools"],"variants":["stroke","filled","duotone"],"sizes":[24],"version":"1.0.0","author":"Travis Peterson","changelog":[{"version":"1.0.0","changes":["Initial release"],"date":"2025-01-01"}]} }
} as const;

export type IconName = keyof typeof iconRegistry;
